name: Daily Jacket Suggester

on:
  schedule:
    - cron: '30 5 * * *'
  workflow_dispatch:

jobs:
  send-jacket-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install python-dotenv

      - name: Run Jacket Suggester
        env:
          GMAIL_ADDRESS: ${{ secrets.GMAIL_ADDRESS }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
        run: python jacket_suggester.py
